### ISSUE TITLE
address_to_puzzle_hash prompt invalid address

### ISSUE THREAD

**Issue by 3461610003** [CMEONE/chia-utils#2]
I use the address substitution function in https://www.chiaexplorer.com/top-addresses to return an invalid address
for example：
`
var puzzle_hash = address_to_puzzle_hash("xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc");
`

**Comment by CMEONE** [comment]
Odd, for me it is returning `'0x98ef93212418c0b75f56de09748d4074d87372423464bea0c2d1b1a2cb557fb3'`, could you please double check to make sure there are no typos?

**Comment by 3461610003** [comment]
> Odd, for me it is returning `'0x98ef93212418c0b75f56de09748d4074d87372423464bea0c2d1b1a2cb557fb3'`, could you please double check to make sure there are no typos?

Why do I execute this code output address is not the same？
`
console.log("address:xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc");
var puzzle_hash = address_to_puzzle_hash("xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc");
console.log("puzzle_hash:" + puzzle_hash);
var address = puzzle_hash_to_address(puzzle_hash);
console.log("address:" + address);
`
output:
address:xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc
puzzle_hash:0x98ef93212418c0b75f56de09748d4074d87372423464bea0c2d1b1a2cb557fb3
address:xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407es4usv9r

**Comment by CMEONE** [comment]
Very weird, my output is:
```
address:xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc
puzzle_hash:0x98ef93212418c0b75f56de09748d4074d87372423464bea0c2d1b1a2cb557fb3
address:xch1nrhexgfyrrqtwh6kmcyhfr2qwnv8xujzx3jtagxz6xc69j6407esad2hqc
```

Maybe there are some inconsistencies across platforms, could you please share operating system and os version, what environment you are using (e.g. Node.js), how you import (requiring from NPM or file) and your Node.js version (`node -v`)?

**Comment by CMEONE** [comment]
@3461610003 Please try running `npm test` in the directory of the program and let me know the results.

**Comment by 3461610003** [comment]
I run it with nodejs and it turns out to be OK，
Before using HTML file, it was problematic to write code into < script > for execution, I am using win10 system. Maybe there is something wrong with the operation. Thank you for your answer。
My code is as follows：
`
<body>
    <script>
        const CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";
        function bech32_polymod(values) {
            let generator = [0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3];
            let chk = 1;
            for(value in values) {
                value = values[value];
                top = chk >> 25
                chk = (chk & 0x1FFFFFF) << 5 ^ value
                for(let i = 0; i < 5; i++) {
                    if((top >> i) & 1) {
                        chk ^= generator[i];
                    } else {
                        chk ^= 0;
                    }
                }
            }
            return chk;
        }


        function bech32_hrp_expand(hrp) {
            let arr = [];
            for(x in hrp) {
                x = hrp[x];
                arr.push(ord(x) >> 5);
            }
            arr.push(0);
            for(x in hrp) {
                x = hrp[x];
                arr.push(ord(x) & 31);
            }
            return arr;
        }


        const M = 0x2BC830A3;


        function bech32_verify_checksum(hrp, data) {
            return bech32_polymod(bech32_hrp_expand(hrp).concat(data)) == M;
        }


        function bech32_create_checksum(hrp, data) {
            let values = bech32_hrp_expand(hrp).concat(data);
            let polymod = bech32_polymod(values.concat([0, 0, 0, 0, 0, 0])) ^ M;
            let arr = [];
            for(let i = 0; i < 6; i++) {
                arr.push((polymod >> 5 * (5 - i)) & 31);
            }
            return arr;
        }


        function bech32_encode(hrp, data) {
            let combined = data.concat(bech32_create_checksum(hrp, data));
            let arr = [hrp, "1"];
            for(d in combined) {
                d = combined[d];
                arr.push(CHARSET[d]);
            }
            return arr.join("");
        }

        function ord(str) {
            return str.charCodeAt(0);
        }

        function any(iterable) {
            for(let i = 0; i < iterable.length; i++) {
                if(iterable[i]) {
                    return true;
                }
            }
            return false;
        }

        function all(iterable) {
            for(let i = 0; i < iterable.length; i++) {
                if(!iterable[i]) {
                    return false;
                }
            }
            return true;
        }


        function bech32_decode(bech) {
            let arr = [];
            for(x in bech) {
                x = bech[x];
                arr.push(ord(x) < 33 || ord(x) > 126);
            }
            if(any(arr) || (bech.toLowerCase() != bech)) {
                return [null, null];
            }
            bech = bech.toLowerCase();
            let pos = bech.lastIndexOf("1");
            if(pos < 1 || pos + 7 > bech.length || bech.length > 90) {
                return [null, null];
            }
            arr = [];
            for(x in bech.slice(pos + 1)) {
                x = bech.slice(pos + 1)[x];
                arr.push(CHARSET.includes(x));
            }
            if(!all(arr)) {
                return [null, null];
            }
            let hrp = bech.slice(0, pos);
            let data = [];
            for(x in bech.slice(pos + 1)) {
                x = bech.slice(pos + 1)[x];
                data.push(CHARSET.indexOf(x));
            }
            // Because I always make mistakes here and give them notes
            // if(!bech32_verify_checksum(hrp, data)) {
            //     return [null, null];
            // }
            return [hrp, data.slice(0, data.length - 6)]
        }


        function convertbits(data, frombits, tobits, pad = true) {
            let acc = 0;
            let bits = 0;
            let ret = [];
            let maxv = (1 << tobits) - 1;
            let max_acc = (1 << (frombits + tobits - 1)) - 1;
            for(value in data) {
                value = data[value];
                if(value < 0 || (value >> frombits))  {
                    throw "Invalid Value";
                }
                acc = ((acc << frombits) | value) & max_acc;
                bits += frombits;
                while(bits >= tobits) {
                    bits -= tobits;
                    ret.push((acc >> bits) & maxv);
                }
            }
            if(pad) {
                if(bits) {
                    ret.push((acc << (tobits - bits)) & maxv);
                }
            } else if(bits >= frombits || ((acc << (tobits - bits)) & maxv)) {
                throw "Invalid bits";
            }
            return ret;
        }


        function encode_puzzle_hash(puzzle_hash, prefix) {
            encoded = bech32_encode(prefix, convertbits(puzzle_hash, 8, 5));
            return encoded;
        }

        function decode_puzzle_hash(address) {
            let d = bech32_decode(address);
            let hrpgot = d[0];
            let data = d[1];
            if(data == null) {
                throw "Invalid Address";
            }
            let decoded = convertbits(data, 5, 8, false);
            return decoded;
        }

        function bytes_to_hex(bytes) {
            if(bytes == null) {
                throw "Argument bytes of method bytes_to_hex is required and does not have a default value.";
            }
            let hex = "";
            for(let i = 0; i < bytes.length; i++) {
                if(bytes[i].toString(16).length == 0) {
                    hex += "00";
                } else if(bytes[i].toString(16).length == 1) {
                    hex += "0" + bytes[i].toString(16);
                } else {
                    hex += bytes[i].toString(16);
                }
            }
            return hex;
        }

        function hex_to_bytes(hex) {
            if(hex == null) {
                throw "Argument hex of method hex_to_bytes is required and does not have a default value.";
            }
            let bytes = new Uint8Array(hex.length / 2);
            for(let i = 0; i < hex.length; i += 2) {
                bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
            }
            return bytes;
        }

        function address_to_puzzle_hash(address) {
            return "0x" + bytes_to_hex(decode_puzzle_hash(address));
        }

        function puzzle_hash_to_address(puzzle_hash) {
            if(puzzle_hash.indexOf("0x") == 0) {
                puzzle_hash = puzzle_hash.substring(2);
            }
            return encode_puzzle_hash(hex_to_bytes(puzzle_hash), "xch");
        }

        function get_coin_info(parent_coin_info, puzzle_hash, amount) {
            amount = amount * 1000000000000;
            if(parent_coin_info.indexOf("0x") == 0) {
                parent_coin_info = parent_coin_info.substring(2);
            }
            if(puzzle_hash.indexOf("0x") == 0) {
                puzzle_hash = puzzle_hash.substring(2);
            }
            const a = Buffer.from(parent_coin_info, 'hex')
            const b = Buffer.from(puzzle_hash, 'hex')
            let amountHex = amount.toString(16);
            if (amountHex.length % 2 == 1) {
                amountHex = '0' + amountHex
            }
            const c = Buffer.from(amountHex, 'hex');

            const d = Buffer.concat([a, b, c], a.length + b.length + c.length);
            const hash = createHash('sha256');
            hash.update(d);
            return "0x" + hash.digest('hex');
        }
        window.onload = function() {
            console.log("address:xch16uc2qsraln6293sfnd4w6epr50lzlc6xnafc090hshlk6k2turwssexsy4");
            var puzzle_hash = address_to_puzzle_hash("xch16uc2qsraln6293sfnd4w6epr50lzlc6xnafc090hshlk6k2turwssexsy4");
            console.log("puzzle_hash:" + puzzle_hash);
            var address = puzzle_hash_to_address(puzzle_hash);
            console.log("address:" + address);
        }
    </script>
</body>
`

**Comment by CMEONE** [comment]
There are some inconsistencies with the browser environment, that is why it says at the top of the code file:

```javascript
if(window != undefined) {
        //window.ChiaUtils = factory();
        throw "chia-utils is not currently supported in the browser.";
}
```

Chia-utils is currently not supported in a browser environment, but we are trying to work out all the inconsistencies to make it work in the browser. Maybe, you could run the code on the server and use something like `express` so that the code is accessible by an API that can be called in the client side?

**Comment by CMEONE** [comment]
@3461610003 We now support the browser, please see the instructions by scrolling down in the install section.
